import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Lead, LeadFilters, LeadStatus } from '@/types/leads';
import { useAuth } from './useAuth';
import { useToast } from './use-toast';

const PAGE_SIZE = 20;

export function useLeads() {
  const { user, isAdmin } = useAuth();
  const { toast } = useToast();
  const [leads, setLeads] = useState<Lead[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalCount, setTotalCount] = useState(0);
  const [filters, setFilters] = useState<LeadFilters>({
    search: '',
    status: 'all',
    assignedTo: 'all',
    dateFrom: '',
    dateTo: '',
  });

  const fetchLeads = useCallback(async () => {
    if (!user) return;

    setLoading(true);
    try {
      let query = supabase
        .from('leads')
        .select('*', { count: 'exact' });

      // Apply filters
      if (filters.search) {
        query = query.or(`company_name.ilike.%${filters.search}%,contact_number.ilike.%${filters.search}%,poc_name.ilike.%${filters.search}%,serial_number.ilike.%${filters.search}%`);
      }

      if (filters.status !== 'all') {
        query = query.eq('status', filters.status);
      }

      if (filters.assignedTo === 'unassigned') {
        query = query.is('assigned_to', null);
      } else if (filters.assignedTo !== 'all') {
        query = query.eq('assigned_to', filters.assignedTo);
      }

      if (filters.dateFrom) {
        query = query.gte('created_at', filters.dateFrom);
      }

      if (filters.dateTo) {
        query = query.lte('created_at', filters.dateTo);
      }

      // Pagination
      const from = (page - 1) * PAGE_SIZE;
      const to = from + PAGE_SIZE - 1;

      query = query
        .order('created_at', { ascending: false })
        .range(from, to);

      const { data, error, count } = await query;

      if (error) throw error;

      setLeads((data as Lead[]) || []);
      setTotalCount(count || 0);
    } catch (error: any) {
      console.error('Error fetching leads:', error);
      toast({
        title: 'Error',
        description: 'Failed to fetch leads',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  }, [user, filters, page, toast]);

  useEffect(() => {
    fetchLeads();
  }, [fetchLeads]);

  // Subscribe to realtime updates
  useEffect(() => {
    const channel = supabase
      .channel('leads-changes')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'leads' },
        () => {
          fetchLeads();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [fetchLeads]);

  const createLead = async (leadData: Partial<Lead>) => {
    if (!user) return { error: 'Not authenticated' };

    try {
      // Auto-assign to creator if not admin
      const autoAssign = !isAdmin;
      
      const insertData = {
        company_name: leadData.company_name || '',
        contact_number: leadData.contact_number || '',
        poc_name: leadData.poc_name || null,
        poc_number: leadData.poc_number || null,
        address: leadData.address || null,
        website: leadData.website || null,
        requirements: leadData.requirements || [],
        other_service: leadData.other_service || null,
        lead_source: leadData.lead_source || null,
        status: leadData.status || 'new_lead',
        remarks: leadData.remarks || null,
        follow_up_date: leadData.follow_up_date || null,
        latitude: leadData.latitude || null,
        longitude: leadData.longitude || null,
        created_by: user.id,
        // Auto-assign to self if not admin
        assigned_to: autoAssign ? user.id : null,
        assigned_by: autoAssign ? user.id : null,
        assigned_at: autoAssign ? new Date().toISOString() : null,
      };

      // serial_number is auto-generated by trigger
      const { data, error } = await supabase
        .from('leads')
        .insert(insertData as any)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Success',
        description: 'Lead created successfully',
      });

      return { data, error: null };
    } catch (error: any) {
      console.error('Error creating lead:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to create lead',
        variant: 'destructive',
      });
      return { data: null, error: error.message };
    }
  };

  const updateLead = async (id: string, updates: Partial<Lead>) => {
    try {
      const { data, error } = await supabase
        .from('leads')
        .update(updates)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Success',
        description: 'Lead updated successfully',
      });

      return { data, error: null };
    } catch (error: any) {
      console.error('Error updating lead:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to update lead',
        variant: 'destructive',
      });
      return { data: null, error: error.message };
    }
  };

  const deleteLead = async (id: string) => {
    try {
      const { error } = await supabase
        .from('leads')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast({
        title: 'Success',
        description: 'Lead deleted successfully',
      });

      return { error: null };
    } catch (error: any) {
      console.error('Error deleting lead:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to delete lead',
        variant: 'destructive',
      });
      return { error: error.message };
    }
  };

  const assignLead = async (leadId: string, userId: string) => {
    if (!user) return { error: 'Not authenticated' };

    try {
      const { data, error } = await supabase
        .from('leads')
        .update({
          assigned_to: userId,
          assigned_by: user.id,
          assigned_at: new Date().toISOString(),
        })
        .eq('id', leadId)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Success',
        description: 'Lead assigned successfully',
      });

      return { data, error: null };
    } catch (error: any) {
      console.error('Error assigning lead:', error);
      toast({
        title: 'Error',
        description: error.message || 'Failed to assign lead',
        variant: 'destructive',
      });
      return { data: null, error: error.message };
    }
  };

  const bulkImportLeads = async (leadsData: Partial<Lead>[]) => {
    if (!user) return { success: 0, errors: ['Not authenticated'] };

    const errors: string[] = [];
    let success = 0;

    for (let i = 0; i < leadsData.length; i++) {
      const leadData = leadsData[i];
      try {
        const insertData = {
          company_name: leadData.company_name || `Import ${i + 1}`,
          contact_number: leadData.contact_number || '-',
          poc_name: leadData.poc_name || null,
          poc_number: leadData.poc_number || null,
          address: leadData.address || null,
          website: leadData.website || null,
          requirements: leadData.requirements || [],
          other_service: leadData.other_service || null,
          lead_source: leadData.lead_source || null,
          status: leadData.status || 'new_lead',
          remarks: leadData.remarks || null,
          follow_up_date: leadData.follow_up_date || null,
          deal_value: leadData.deal_value || null,
          created_by: user.id,
        };

        const { error } = await supabase
          .from('leads')
          .insert(insertData as any);

        if (error) throw error;
        success++;
      } catch (error: any) {
        errors.push(`Row ${i + 1}: ${error.message}`);
      }
    }

    if (success > 0) {
      toast({
        title: 'Import Complete',
        description: `Successfully imported ${success} leads`,
      });
      fetchLeads();
    }

    return { success, errors };
  };

  const totalPages = Math.ceil(totalCount / PAGE_SIZE);

  return {
    leads,
    loading,
    page,
    setPage,
    totalPages,
    totalCount,
    filters,
    setFilters,
    createLead,
    updateLead,
    deleteLead,
    assignLead,
    bulkImportLeads,
    refetch: fetchLeads,
  };
}
